{
   "openapi": "3.0.0",
   "info": {
      "title": "Shotstack",
      "version": "v1",
      "description": "The Shotstack API is a video editing service that allows for the programatic creation of videos using JSON. You can configure an edit and POST it the Shotstack API which will take render your video and provide a file location when complete. For more details check https://shotstack.io"
   },
   "servers": [
      {
         "url": "https://api.shotstack.io/{version}",
         "variables": {
            "version": {
               "enum": [
                  "v1",
                  "stage"
                ],
               "default": "v1"
            }
         }
      }
   ],
   "paths": {
      "/render": {
         "post": {
            "responses": {
               "201": {
                  "description": "",
                  "content": {
                     "application/json": {
                        "example": {
                           "success": true,
                           "message": "Created",
                           "response": {
                              "message": "Render Successfuly Queued",
                              "id": "2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7"
                           }
                        },
                        "schema": {
                           "$ref": "#/components/schemas/QueuedResponse"
                        }
                     }
                  }
               }
            },
            "description": "Render the contents of a timeline as a video file.",
            "operationId": "postRender",
            "requestBody": {
               "content": {
                  "application/json": {
                     "example": {
                        "timeline": {
                           "soundtrack": {
                              "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/music.mp3",
                              "effect": "fadeInFadeOut"
                           },
                           "background": "#000000",
                           "tracks": [
                              {
                                 "clips": [
                                    {
                                       "asset": {
                                          "type": "title",
                                          "text": "Hello World",
                                          "style": "minimal"
                                       },
                                       "start": 0,
                                       "length": 4,
                                       "transition": {
                                          "in": "fade",
                                          "out": "fade"
                                       },
                                       "effect": "slideRight"
                                    },
                                    {
                                       "asset": {
                                          "type": "image",
                                          "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-image.jpg"
                                       },
                                       "start": 3,
                                       "length": 4,
                                       "effect": "zoomIn",
                                       "filter": "greyscale"
                                    }
                                 ]
                              },
                              {
                                 "clips": [
                                    {
                                       "asset": {
                                          "type": "video",
                                          "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-clip-1.mp4",
                                          "trim": 10.5
                                       },
                                       "start": 7,
                                       "length": 4.5
                                    },
                                    {
                                       "asset": {
                                          "type": "video",
                                          "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-clip-2.mp4",
                                          "volume": 0.5
                                       },
                                       "start": 11.5,
                                       "length": 5,
                                       "transition": {
                                          "out": "wipeLeft"
                                       }
                                    }
                                 ]
                              }
                           ]
                        },
                        "output": {
                           "format": "mp4",
                           "resolution": "sd"
                        }
                     },
                     "schema": {
                        "$ref": "#/components/schemas/Edit"
                     }
                  }
               },
               "required": true
            },
            "security": [
               {
                  "DeveloperKey": []
               }
            ],
            "tags": [
               "Endpoints"
            ]
         }
      },
      "/render/{id}": {
         "get": {
            "responses": {
               "200": {
                  "description": "",
                  "content": {
                     "application/json": {
                        "example": {
                           "success": true,
                           "message": "OK",
                           "response": {
                              "status": "rendering",
                              "id": "2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7",
                              "owner": "5ca6hu7s9k",
                              "url": "https://shotstack-api-v1-output.s3-ap-southeast-2.amazonaws.com/5ca6hu7s9k/2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7.mp4",
                              "data": {
                                 "timeline": {
                                    "soundtrack": {
                                       "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/music.mp3",
                                       "effect": "fadeInFadeOut"
                                    },
                                    "background": "#000000",
                                    "tracks": [
                                       {
                                          "clips": [
                                             {
                                                "asset": {
                                                   "type": "title",
                                                   "text": "Hello World",
                                                   "style": "minimal"
                                                },
                                                "start": 0,
                                                "length": 4,
                                                "transition": {
                                                   "in": "fade",
                                                   "out": "fade"
                                                },
                                                "effect": "slideRight"
                                             },
                                             {
                                                "asset": {
                                                   "type": "image",
                                                   "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-image.jpg"
                                                },
                                                "start": 3,
                                                "length": 4,
                                                "effect": "zoomIn",
                                                "filter": "greyscale"
                                             }
                                          ]
                                       },
                                       {
                                          "clips": [
                                             {
                                                "asset": {
                                                   "type": "video",
                                                   "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-clip-1.mp4",
                                                   "trim": 10.5
                                                },
                                                "start": 7,
                                                "length": 4.5
                                             },
                                             {
                                                "asset": {
                                                   "type": "video",
                                                   "src": "https://s3-ap-northeast-1.amazonaws.com/my-bucket/my-clip-2.mp4",
                                                   "volume": 0.5
                                                },
                                                "start": 11.5,
                                                "length": 5,
                                                "transition": {
                                                   "out": "wipeLeft"
                                                }
                                             }
                                          ]
                                       }
                                    ]
                                 },
                                 "output": {
                                    "format": "mp4",
                                    "resolution": "sd"
                                 }
                              },
                              "created": "2018-05-06T03:33:25.425Z",
                              "updated": "2018-05-06T03:33:48.521Z"
                           }
                        },
                        "schema": {
                           "$ref": "#/components/schemas/RenderResponse"
                        }
                     }
                  }
               }
            },
            "description": "Get the rendering status, video url and details of a timeline by ID.",
            "operationId": "getRender",
            "security": [
               {
                  "DeveloperKey": []
               }
            ],
            "tags": [
               "Endpoints"
            ]
         },
         "parameters": [
            {
               "name": "id",
               "in": "path",
               "required": true,
               "schema": {
                  "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
                  "type": "string"
               },
               "description": "The id of the timeline render task in UUID format"
            }
         ]
      }
   },
   "components": {
      "schemas": {
         "Edit": {
            "description": "An edit defines the content of the video in a timeline and the output format.",
            "properties": {
               "timeline": {
                  "$ref": "#/components/schemas/Timeline"
               },
               "output": {
                  "$ref": "#/components/schemas/Output"
               }
            },
            "required": [
               "timeline",
               "output"
            ],
            "type": "object"
         },
         "Timeline": {
            "description": "A timeline represents the contents of a video edit over time, in seconds. A timeline consists of layers called tracks. Tracks are composed of titles, images or video segments referred to as clips which are placed along the track at specific starting point and lasting for a specific amount of time.",
            "properties": {
               "soundtrack": {
                  "description": "A music or audio soundtrack file in mp3 format.",
                  "$ref": "#/components/schemas/Soundtrack"
               },
               "background": {
                  "description": "A hexidecimal value for the timeline background colour. Defaults to black (#000000).",
                  "type": "string"
               },
               "tracks": {
                  "description": "A timeline consists of an array of tracks, each track containing clips. Tracks are layered on top of each other in the same order they are added to the array with the top most track layered over the top of those below it. Ensure that a track containing titles is the top most track so that it is displayed above videos and images.",
                  "type": "array",
                  "items": {
                     "$ref": "#/components/schemas/Track"
                  }
               }
            },
            "required": [
               "tracks"
            ],
            "type": "object"
         },
         "Soundtrack": {
            "description": "A music or audio file in mp3 format that plays for the duration of the rendered video or the length of the audio file, which ever is shortest.",
            "properties": {
               "src": {
                  "description": "The URL of the mp3 audio file. The URL must be publicly accessible or include credentials.",
                  "type": "string"
               },
               "effect": {
                  "description": "The effect to apply to the audio file",
                  "enum": [
                     "fadeIn",
                     "fadeOut",
                     "fadeInFadeOut"
                  ],
                  "type": "string"
               }
            },
            "required": [
               "src"
            ],
            "type": "object"
         },
         "Track": {
            "description": "A track contains an array of clips. Tracks are layered on top of each other in the order in the array. The top most track will render on top of those below it.",
            "properties": {
               "clips": {
                  "description": "An array of Clips comprising of TitleClip, ImageClip or VideoClip.",
                  "type": "array",
                  "items": {
                     "$ref": "#/components/schemas/Clip"
                  }
               }
            },
            "required": [
               "clips"
            ],
            "type": "object"
         },
         "Clip": {
            "description": "A clip is a container for a specific type of asset, i.e. a title, photo or video. You use a Clip to define when an asset will display on the timeline, how long it will play for and transitions and effects to apply to it.",
            "properties": {
               "asset": {
                  "description": "The type of asset to display for the duration of this Clip. Value must be one of <b>TitleAsset</b>, <b>ImageAsset</b> or <b>VideoAsset</b>.",
                  "oneOf": [
                     {
                        "$ref": "#/components/schemas/TitleAsset"
                     },
                     {
                        "$ref": "#/components/schemas/ImageAsset"
                     },
                     {
                        "$ref": "#/components/schemas/VideoAsset"
                     }
                  ]
               },
               "start": {
                  "description": "The start position of the Clip on the timeline, in seconds.",
                  "type": "number"
               },
               "length": {
                  "description": "The length, in seconds, the Clip should play for.",
                  "type": "number"
               },
               "transition": {
                  "$ref": "#/components/schemas/Transition"
               },
               "effect": {
                  "description": "A motion effect to apply to the Clip.",
                  "enum": [
                     "zoomIn",
                     "zoomOut",
                     "slideLeft",
                     "slideRight",
                     "slideUp",
                     "slideDown"
                  ],
                  "type": "string"
               },
               "filter": {
                  "description": "A filter effect to apply to the Clip.",
                  "enum": [
                     "boost",
                     "contrast",
                     "darken",
                     "greyscale",
                     "lighten",
                     "muted",
                     "negative"
                  ],
                  "type": "string"
               }
            },
            "required": [
               "asset",
               "start",
               "length"
            ],
            "type": "object"
         },
         "TitleAsset": {
            "description": "The TitleAsset clip type lets you create video titles from a text string and apply styling and positioning.",
            "type": "object",
            "properties": {
               "type": {
                  "default": "title",
                  "description": "The type of asset - set to <b>title</b> for titles.",
                  "type": "string"
               },
               "text": {
                  "description": "The title text string - i.e. \"My Title\".",
                  "type": "string"
               },
               "style": {
                  "description": "Uses a preset to apply font properties and stylng to the title.",
                  "enum": [
                     "minimal",
                     "blockbuster",
                     "vogue",
                     "sketchy",
                     "skinny",
                     "chunk",
                     "chunkLight",
                     "marker",
                     "future",
                     "subtitle"
                  ],
                  "type": "string"
               },
               "color": {
                  "default": "white",
                  "description": "Set the text color using HTML color notation including hexidecimal, rgb, rgba and  color name. Transparency is supported by setting the last two characters of a hex string,  i.e. #ffffff33 or using rgba, i.e. rgba(255, 255, 255, 0.5).",
                  "type": "string"
               },
               "size": {
                  "default": "medium",
                  "description": "Set the relative size of the text using predefined sizes from xx-small to xx-large.",
                  "enum": [
                     "xx-small",
                     "x-small",
                     "small",
                     "medium",
                     "large",
                     "x-large",
                     "xx-large"
                  ],
                  "type": "string"
               },
               "background": {
                  "description": "Apply a background color behind the text using HTML color notation with support for  transparency. Useful for subtitles.",
                  "type": "string"
               },
               "position": {
                  "default": "center",
                  "description": "Place the title in one of nine predefined positions of the viewport.",
                  "enum": [
                     "top",
                     "topRight",
                     "right",
                     "bottomRight",
                     "bottom",
                     "bottomLeft",
                     "left",
                     "topLeft",
                     "center"
                  ],
                  "type": "string"
               },
               "offset": {
                  "description": "Offset the location of the title relative to it's position on the screen.",
                  "$ref": "#/components/schemas/Offset"
               }
            },
            "required": [
               "type",
               "text"
            ]
         },
         "ImageAsset": {
            "description": "The ImageAsset is used to create video from images. The src must be a publicly accesible URL to an image resource such as a jpg or png file.",
            "type": "object",
            "properties": {
               "type": {
                  "default": "image",
                  "description": "The type of asset - set to <b>image</b> for images.",
                  "type": "string"
               },
               "src": {
                  "description": "The image source URL. The URL must be publicly accessible or include credentials.",
                  "type": "string"
               }
            },
            "required": [
               "type",
               "src"
            ]
         },
         "VideoAsset": {
            "description": "The VideoAsset is used to create video sequences from video files. The src must be a publicly accesible URL to a video resource such as an mp4 file. The in and out attributes of the parent Clip let you trim the video file by setting the start and end point to use.",
            "type": "object",
            "properties": {
               "type": {
                  "default": "video",
                  "description": "The type of asset - set to <b>video</b> for videos.",
                  "type": "string"
               },
               "src": {
                  "description": "The video source URL. The URL must be publicly accessible or include credentials.",
                  "type": "string"
               },
               "trim": {
                  "description": "The start trim point of the clip, in seconds (defaults to 0). Videos will start from the in trim point. The video will play until the file ends or the Clip length is reached.",
                  "type": "number"
               },
               "volume": {
                  "description": "Set the volume for the clip between 0 and 1 where 0 is muted and 1 is full volume (defaults to 0).",
                  "type": "number"
               }
            },
            "required": [
               "type",
               "src"
            ]
         },
         "Transition": {
            "description": "In and out transitions for a clip - i.e. fade in and fade out",
            "properties": {
               "in": {
                  "description": "The transition in",
                  "enum": [
                     "fade",
                     "wipeLeft",
                     "wipeRight"
                  ],
                  "type": "string"
               },
               "out": {
                  "description": "The transition out",
                  "enum": [
                     "fade",
                     "wipeLeft",
                     "wipeRight"
                  ],
                  "type": "string"
               }
            },
            "type": "object"
         },
         "Offset": {
            "description": "Offsets the position of an asset horizontally or vertically by a relative distance.",
            "properties": {
               "x": {
                  "description": "Offset an asset on the horizontal axis (left or right), range varies from -1 to 1.",
                  "type": "number"
               },
               "y": {
                  "description": "Offset an asset on the vertical axis (up or down), range varies from -1 to 1.",
                  "type": "number"
               }
            },
            "type": "object"
         },
         "Output": {
            "description": "The video output format",
            "properties": {
               "format": {
                  "enum": [
                     "mp4",
                     "gif"
                  ],
                  "type": "string"
               },
               "resolution": {
                  "enum": [
                     "preview",
                     "mobile",
                     "sd",
                     "hd",
                     "1080"
                  ],
                  "type": "string"
               }
            },
            "required": [
               "format",
               "resolution"
            ],
            "type": "object"
         },
         "QueuedResponse": {
            "properties": {
               "success": {
                  "type": "boolean"
               },
               "message": {
                  "type": "string"
               },
               "response": {
                  "$ref": "#/components/schemas/QueuedResponseData"
               }
            },
            "required": [
               "success",
               "message",
               "response"
            ],
            "type": "object"
         },
         "QueuedResponseData": {
            "properties": {
               "message": {
                  "description": "Success response message",
                  "type": "string"
               },
               "id": {
                  "description": "The id of the render task in UUID format",
                  "type": "string"
               }
            },
            "required": [
               "message",
               "id"
            ],
            "type": "object"
         },
         "RenderResponse": {
            "properties": {
               "success": {
                  "type": "boolean"
               },
               "message": {
                  "type": "string"
               },
               "response": {
                  "$ref": "#/components/schemas/RenderResponseData"
               }
            },
            "required": [
               "success",
               "message",
               "response"
            ],
            "type": "object"
         },
         "RenderResponseData": {
            "properties": {
               "status": {
                  "description": "The status of the render task",
                  "enum": [
                     "queued",
                     "fetching",
                     "rendering",
                     "saving",
                     "done",
                     "failed"
                  ],
                  "type": "string"
               },
               "id": {
                  "description": "The id of the render task in UUID format",
                  "type": "string"
               },
               "owner": {
                  "description": "The owner id of the render task",
                  "type": "string"
               },
               "url": {
                  "description": "The URL of the final video. This will only be available if status is done.",
                  "type": "string"
               },
               "data": {
                  "description": "The timeline and output data to be rendered",
                  "$ref": "#/components/schemas/Edit"
               },
               "created": {
                  "description": "The time the render task was initially queued",
                  "type": "string"
               },
               "updated": {
                  "description": "The time the render status was last updated",
                  "type": "string"
               }
            },
            "required": [
               "status",
               "id",
               "owner",
               "data",
               "created",
               "updated"
            ],
            "type": "object"
         }
      },
      "responses": {},
      "parameters": {},
      "examples": {},
      "requestBodies": {},
      "headers": {},
      "securitySchemes": {
         "DeveloperKey": {
            "description": "Set the header named below with your provided key for the correct environment (v1 or stage). Include the header in all calls to the API that are secured with a key.",
            "type": "apiKey",
            "in": "header",
            "name": "x-api-key"
         }
      },
      "links": {},
      "callbacks": {}
   }
}